settings:
  title: 'ANi Status'
  url: 'https://status.ani.rip' # used for Slack messages
  logo: 'https://raw.githubusercontent.com/RyanL-29/aniopen/master/aniiconw.png' # image in ./public/ folder
  daysInHistogram: 100 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: '所有系統均正常運作中'
  notAllmonitorsOperational: '有部分系統出現問題'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Error'
  monitorLabelNoData: '沒有數據'
  dayInHistogramNoData: '沒有數據'
  dayInHistogramOperational: '正常'
  dayInHistogramNotOperational: ' 錯誤' # xx incident(s) recorded

monitors:
  - id: ANiSystem # unique identifier
    name: ANi System
    description: '主要伺服器' # default=empty
    url: 'http://aniprivate.mynetgear.com/404.html' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false

  - id: ANiStorage
    name: ANi NAS
    description: '儲存伺服器'
    url: 'http://aniprivate.mynetgear.com/404.html'
    method: GET
    expectStatus: 200
    followRedirect: true # should fetch follow redirects, default=false
    
  - id: OpenANi
    name: Open ANi
    url: 'https://aniopen.a-ni.workers.dev/'
    method: GET
    expectStatus: 200
    followRedirect: true # should fetch follow redirects, default=false
    
  - id: ANiAPI
    name: ANi API
    url: 'https://api.ani.rip/ani/api/anigamer_new.xml'
    method: GET
    expectStatus: 200
    followRedirect: true # should fetch follow redirects, default=false
